apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
spec:
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: products_db # Mude para o nome do seu banco
        - name: POSTGRES_PASSWORD
          value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db # Este nome cria o DNS interno que o Spring procura
spec:
  selector:
    app: postgres-db
  ports:
    - port: 5432