apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: NodePort # Expõe o serviço no host
  selector:
    app: product-service # Liga ao Deployment pelo label
  ports:
    - protocol: TCP
      port: 80 # Porta interna do Service
      targetPort: 8080 # Porta do container
      nodePort: 30080 # Porta acessível no host (30000-32767)